### ISSUE TITLE
Failed build creates pass

### ISSUE THREAD

**Issue by KenwoodFox** [Ewpratten/FRC-actions#3]
```
BUILD FAILED in 12s
Compilation Error!
GradleRIO detected this build failed due to a Compile Error (compileJava).
Check that all your files are saved, then scroll up in this log for more information.
```

My build failed but I still got a checkmark, what's up with that?
![image](https://user-images.githubusercontent.com/31870999/74588138-0722dc00-4fc8-11ea-9da5-3e53922b4189.png)

**Comment by Ewpratten** [comment]
That is weird. Can I see the yml config you are using?

@frc5024 has had no issues with:
```yml
name: FRC Build & Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2-beta
    - name: FRC Build & Test
      uses: ewpratten/FRC-actions@v1
      with:
        build_mode: 'all'
```
